services:
  blazor-app:
    build: .
    container_name: blazor-app
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=HRdb;Username=postgres;Password=postgres"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: HRdb
    ports:
      - "5432:5432"
